import Typography from '@/components/Home/Typography'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Typography and side Image */}
      <div className='grid grid-cols-1 md:grid-cols-3 gap-2 mt-20'>
        <Typography />
        <div className='max-md:order-1 flex flex-col items-center  mr-10'>
          <img src='assets/01.png'></img>
        </div>
      </div>

      {/* Carousel */}
      {/* <Carousel items={items} /> */}
      <div className='w-full flex justify-center mt-20'>
        <img src='assets/cara4.png'></img>
      </div>
    </>
  )
}
